@extends('layouts.app')

@section('title', 'Payslip - ' . $payroll->period_start->format('M d') . ' to ' . $payroll->period_end->format('M d, Y'))

@section('content')
<div class="main-content">
    <div style="margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between;" class="no-print">
        <a href="{{ route('employee.payroll.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back to Payslips</a>
        <button onclick="window.print()" class="btn btn-primary"><i class="fas fa-print"></i> Print / Save as PDF</button>
    </div>

    <div class="payslip">
        <div class="payslip-header">
            <div>
                <h2>{{ config('app.name', 'Company') }}</h2>
                <p class="payslip-subtitle">Human Resource Management System</p>
            </div>
            <div class="payslip-header-right">
                <h3>PAYSLIP</h3>
                <span>Receipt #{{ str_pad($payroll->id, 6, '0', STR_PAD_LEFT) }}</span>
            </div>
        </div>

        <div class="payslip-status">
            <span class="badge badge-success"><i class="fas fa-check-circle"></i> Approved</span>
        </div>

        <div class="payslip-section">
            <div class="payslip-col">
                <h4>Employee Information</h4>
                <p><strong>Name:</strong> {{ $payroll->employee->name }}</p>
                <p><strong>Email:</strong> {{ $payroll->employee->email }}</p>
                <p><strong>Phone:</strong> {{ $payroll->employee->phone ?? 'Not provided' }}</p>
            </div>
            <div class="payslip-col">
                <h4>Pay Period</h4>
                <p><strong>Start Date:</strong> {{ $payroll->period_start->format('F d, Y') }}</p>
                <p><strong>End Date:</strong> {{ $payroll->period_end->format('F d, Y') }}</p>
                <p><strong>Issued:</strong> {{ $payroll->updated_at->format('F d, Y') }}</p>
            </div>
        </div>

        <div class="payslip-table-container">
            <table class="payslip-table">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th style="text-align: right;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Total Hours Worked</td>
                        <td style="text-align: right;">{{ number_format($payroll->total_hours, 2) }} hrs</td>
                    </tr>
                    <tr>
                        <td>Hourly Rate</td>
                        <td style="text-align: right;">${{ number_format($payroll->hourly_rate, 2) }} / hr</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td><strong>Gross Pay</strong></td>
                        <td style="text-align: right;"><strong>${{ number_format($payroll->total_pay, 2) }}</strong></td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="payslip-total">
            <span>Net Pay</span>
            <span class="payslip-total-amount">${{ number_format($payroll->total_pay, 2) }}</span>
        </div>

        <div class="payslip-footer">
            <p>This is a system-generated payslip and does not require a signature.</p>
            <p>Generated by {{ $payroll->generatedBy->name ?? 'HR Department' }} &middot; {{ config('app.name', 'Company') }}</p>
        </div>
    </div>
</div>

<style>
    .payslip {
        max-width: 750px;
        margin: 0 auto;
        background: white;
        border: 1px solid #e5e7eb;
        border-radius: 10px;
        padding: 36px 40px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
    }

    .payslip-header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        border-bottom: 2px solid #0d9488;
        padding-bottom: 18px;
        margin-bottom: 18px;
    }

    .payslip-header h2 {
        color: #0d9488;
        font-size: 1.4rem;
        margin: 0;
    }

    .payslip-subtitle {
        font-size: 0.8rem;
        color: #888;
        margin-top: 4px;
    }

    .payslip-header-right {
        text-align: right;
    }

    .payslip-header-right h3 {
        margin: 0;
        color: #333;
        letter-spacing: 1px;
    }

    .payslip-header-right span {
        font-size: 0.8rem;
        color: #999;
    }

    .payslip-status {
        margin-bottom: 20px;
    }

    .payslip-section {
        display: flex;
        justify-content: space-between;
        gap: 30px;
        margin-bottom: 24px;
        flex-wrap: wrap;
    }

    .payslip-col {
        flex: 1;
        min-width: 220px;
    }

    .payslip-col h4 {
        font-size: 0.8rem;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        color: #999;
        margin-bottom: 8px;
    }

    .payslip-col p {
        font-size: 0.9rem;
        color: #333;
        margin-bottom: 4px;
    }

    .payslip-table-container {
        margin-bottom: 20px;
    }

    .payslip-table {
        width: 100%;
        border-collapse: collapse;
    }

    .payslip-table th {
        text-align: left;
        font-size: 0.8rem;
        text-transform: uppercase;
        color: #999;
        padding: 8px 0;
        border-bottom: 1px solid #e5e7eb;
    }

    .payslip-table td {
        padding: 10px 0;
        font-size: 0.95rem;
        border-bottom: 1px solid #f1f5f9;
    }

    .payslip-table tfoot td {
        border-top: 2px solid #e5e7eb;
        border-bottom: none;
        padding-top: 14px;
        font-size: 1rem;
    }

    .payslip-total {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background: #f0fdfa;
        border: 1px solid #99f6e4;
        border-radius: 8px;
        padding: 16px 20px;
        margin-bottom: 24px;
    }

    .payslip-total span:first-child {
        font-weight: 600;
        color: #0f766e;
    }

    .payslip-total-amount {
        font-size: 1.5rem;
        font-weight: 700;
        color: #0d9488;
    }

    .payslip-footer {
        text-align: center;
        font-size: 0.8rem;
        color: #999;
        border-top: 1px solid #e5e7eb;
        padding-top: 16px;
    }

    .payslip-footer p {
        margin-bottom: 4px;
    }

    @media print {
        .sidebar, .no-print {
            display: none !important;
        }

        .main-content {
            margin-left: 0 !important;
        }

        .payslip {
            box-shadow: none;
            border: none;
        }
    }
</style>
@endsection