@extends('layouts.app')

@section('title', 'Payslip - ' . $payroll->period_start->format('M d') . ' to ' . $payroll->period_end->format('M d, Y'))

@section('content')
<div class="main-content">
    <div style="margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between;" class="no-print">
        <a href="{{ route('employee.payroll.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back to Payslips</a>
        <button onclick="window.print()" class="btn btn-primary"><i class="fas fa-print"></i> Print / Save as PDF</button>
    </div>

    <div class="payslip">
        <div class="payslip-header">
            <div>
                <h2>ChillVibe HR</h2>
                <p class="payslip-subtitle">Human Resource Management System</p>
            </div>
            <div class="payslip-header-right">
                <h3>PAYSLIP</h3>
                <span>Receipt #{{ str_pad($payroll->id, 6, '0', STR_PAD_LEFT) }}</span>
            </div>
        </div>

        <div class="payslip-status">
            <span class="badge badge-success"><i class="fas fa-check-circle"></i> Approved</span>
        </div>

        <div class="payslip-section">
            <div class="payslip-col">
                <h4>Employee Information</h4>
                <p><strong>Name:</strong> {{ $payroll->employee->name }}</p>
                <p><strong>Email:</strong> {{ $payroll->employee->email }}</p>
                <p><strong>Phone:</strong> {{ $payroll->employee->phone ?? 'Not provided' }}</p>
            </div>
            <div class="payslip-col">
                <h4>Pay Period</h4>
                <p><strong>Start Date:</strong> {{ $payroll->period_start->format('F d, Y') }}</p>
                <p><strong>End Date:</strong> {{ $payroll->period_end->format('F d, Y') }}</p>
                <p><strong>Issued:</strong> {{ $payroll->updated_at->format('F d, Y') }}</p>
            </div>
        </div>

        <div class="payslip-table-container">
            <table class="payslip-table">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th style="text-align: right;">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Total Hours Worked</td>
                        <td style="text-align: right;">{{ number_format($payroll->total_hours, 2) }} hrs</td>
                    </tr>
                    <tr>
                        <td>Hourly Rate</td>
                        <td style="text-align: right;">${{ number_format($payroll->hourly_rate, 2) }} / hr</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td><strong>Gross Pay</strong></td>
                        <td style="text-align: right;"><strong>${{ number_format($payroll->total_pay, 2) }}</strong></td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="payslip-total">
            <span>Net Pay</span>
            <span class="payslip-total-amount">${{ number_format($payroll->total_pay, 2) }}</span>
        </div>

        <div class="payslip-footer">
            <p>This is a system-generated payslip and does not require a signature.</p>
            <p>Generated by {{ $payroll->generatedBy->name ?? 'HR Department' }} &middot; {{ config('app.name', 'Company') }}</p>
        </div>
    </div>
</div>

@endsection